name: WASM Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  wasm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build WASM
        run: ./scripts/build_wasm.sh
      - name: Run WASM tests
        run: cargo test --target wasm32-unknown-unknown
