use std::fmt::Write as FmtWrite;
use std::fs::File;
use std::io::Write;
use std::path::Path;

use crate::errors::CostPilotError;

/// Generates static HTML wrapper for SVG graphs
pub struct HtmlGenerator;

impl HtmlGenerator {
    /// Wrap SVG in HTML document
    pub fn wrap_svg(svg: &str, title: &str) -> String {
        let mut html = String::new();

        writeln!(&mut html, "<!DOCTYPE html>").unwrap();
        writeln!(&mut html, "<html lang=\"en\">").unwrap();
        writeln!(&mut html, "<head>").unwrap();
        writeln!(&mut html, "  <meta charset=\"UTF-8\">").unwrap();
        writeln!(&mut html, "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">").unwrap();
        writeln!(&mut html, "  <title>{}</title>", Self::escape_html(title)).unwrap();
        writeln!(&mut html, "  <style>").unwrap();
        writeln!(&mut html, "{}", Self::get_styles()).unwrap();
        writeln!(&mut html, "  </style>").unwrap();
        writeln!(&mut html, "</head>").unwrap();
        writeln!(&mut html, "<body>").unwrap();
        writeln!(&mut html, "  <div class=\"container\">").unwrap();
        writeln!(&mut html, "    <header>").unwrap();
        writeln!(&mut html, "      <h1>{}</h1>", Self::escape_html(title)).unwrap();
        writeln!(&mut html, "      <p class=\"subtitle\">Cost trend visualization</p>").unwrap();
        writeln!(&mut html, "    </header>").unwrap();
        writeln!(&mut html, "    <div class=\"graph-container\">").unwrap();
        writeln!(&mut html, "{}", svg).unwrap();
        writeln!(&mut html, "    </div>").unwrap();
        writeln!(&mut html, "    <footer>").unwrap();
        writeln!(&mut html, "      <p>Generated by CostPilot</p>").unwrap();
        writeln!(&mut html, "    </footer>").unwrap();
        writeln!(&mut html, "  </div>").unwrap();
        writeln!(&mut html, "</body>").unwrap();
        writeln!(&mut html, "</html>").unwrap();

        html
    }

    /// Generate HTML file with embedded SVG
    pub fn generate_file<P: AsRef<Path>>(
        path: P,
        svg: &str,
        title: &str,
    ) -> Result<(), CostPilotError> {
        let html = Self::wrap_svg(svg, title);
        
        let mut file = File::create(path.as_ref()).map_err(|e| {
            CostPilotError::io_error(format!("Failed to create HTML file: {}", e))
        })?;

        file.write_all(html.as_bytes()).map_err(|e| {
            CostPilotError::io_error(format!("Failed to write HTML: {}", e))
        })?;

        Ok(())
    }

    /// Get CSS styles for HTML wrapper
    fn get_styles() -> &'static str {
        r#"
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 20px;
    }

    .container {
      background: white;
      border-radius: 12px;
      box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
      max-width: 1200px;
      width: 100%;
      padding: 40px;
    }

    header {
      text-align: center;
      margin-bottom: 30px;
    }

    h1 {
      font-size: 2.5rem;
      color: #1a202c;
      margin-bottom: 10px;
    }

    .subtitle {
      font-size: 1.1rem;
      color: #718096;
    }

    .graph-container {
      background: #f7fafc;
      border-radius: 8px;
      padding: 20px;
      margin: 20px 0;
      display: flex;
      justify-content: center;
    }

    svg {
      max-width: 100%;
      height: auto;
    }

    footer {
      text-align: center;
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      color: #718096;
      font-size: 0.9rem;
    }

    @media (max-width: 768px) {
      .container {
        padding: 20px;
      }

      h1 {
        font-size: 1.8rem;
      }

      .subtitle {
        font-size: 1rem;
      }
    }
        "#
    }

    /// Escape HTML special characters
    fn escape_html(text: &str) -> String {
        text.replace('&', "&amp;")
            .replace('<', "&lt;")
            .replace('>', "&gt;")
            .replace('"', "&quot;")
            .replace('\'', "&#39;")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::NamedTempFile;

    #[test]
    fn test_wrap_svg() {
        let svg = r#"<svg><circle cx="50" cy="50" r="40"/></svg>"#;
        let html = HtmlGenerator::wrap_svg(svg, "Test Graph");
        
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("<title>Test Graph</title>"));
        assert!(html.contains(svg));
        assert!(html.contains("</html>"));
    }

    #[test]
    fn test_escape_html() {
        let text = "<script>alert('xss')</script>";
        let escaped = HtmlGenerator::escape_html(text);
        
        assert!(!escaped.contains("<script>"));
        assert!(escaped.contains("&lt;script&gt;"));
    }

    #[test]
    fn test_generate_file() {
        let temp_file = NamedTempFile::new().unwrap();
        let svg = r#"<svg><circle cx="50" cy="50" r="40"/></svg>"#;
        
        let result = HtmlGenerator::generate_file(temp_file.path(), svg, "Test");
        assert!(result.is_ok());
        
        let contents = std::fs::read_to_string(temp_file.path()).unwrap();
        assert!(contents.contains("<!DOCTYPE html>"));
        assert!(contents.contains(svg));
    }

    #[test]
    fn test_styles_included() {
        let svg = r#"<svg></svg>"#;
        let html = HtmlGenerator::wrap_svg(svg, "Test");
        
        assert!(html.contains("<style>"));
        assert!(html.contains("font-family"));
        assert!(html.contains(".container"));
    }
}
